### ISSUE TITLE
U- shaped layout of senators in Rome

### ISSUE THREAD

**Issue by BrentD2004** [iamlogand/republic-of-rome-online#147]
![image](https://github.com/iamlogand/republic-of-rome-online/assets/127432419/b7957c9d-330b-46cb-a608-edbf59199373)
NB: section on the right of the image is in relation to the voting layout that I would like to see added to this project. Also bottom left 'U' is the prefered layout.

**Comment by iamlogand** [comment]
Closing because this was delivered by #436
